/* MO Fitness AI — bilingual chat UI */
(()=>{
const ENDPOINT='https://mo-fitness-ai.moh-oglah.workers.dev';
const ar=()=>document.documentElement.lang!=='en';
const T=(a,e)=>ar()?a:e;
const hasArabic=text=>/[\u0600-\u06FF]/.test(String(text||''));
const normalize=text=>String(text||'').toLowerCase().normalize('NFKC').replace(/[ًٌٍَُِّْـ]/g,'').replace(/[أإآ]/g,'ا').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[^\u0600-\u06ffa-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();
const exerciseTerms=[
'تمرين','تمارين','تمرن','تدريب','سكوات','قرفصاء','ضغط','بوش اب','بوش ابس','عقلة','بلانك','لانجز','اندفاع','ديدلفت','رفعة','سحب','تجديف','بنش','دمبل','دنبل','باربل','بار','كيبل','كابل','عضلة','عضلات','صدر','ظهر','كتف','اكتاف','رجل','ارجل','فخذ','بايسبس','ترايسبس','بطن','كور','عدة','عدات','تكرار','تكرارات','مجموعة','مجموعات','احماء','اطالة','تمدد','كارديو',
'exercise','exercises','workout','workouts','training','train','squat','pushup','push-up','pullup','pull-up','plank','lunge','deadlift','row','bench','dumbbell','barbell','cable','muscle','muscles','chest','back','shoulder','shoulders','legs','leg','biceps','triceps','core','abs','rep','reps','set','sets','warmup','warm-up','stretch','stretching','cardio'
];
const blockedTerms=[
'سياسة','انتخابات','رئيس','حكومة','اخبار','خبر','طقس','سفر','فندق','مطعم','طبخ','وصفة','برمجة','كود','اسهم','استثمار','دين','فتوى','قران','دواء','ادوية','تشخيص','علاج','مرض','سكري','ضغط الدم','حمل','اصابة','اصابات','الم','دوخة',
'تغذيه','غذاء','غذائي','نظام غذائي','حميه','دايت','اكل','وجبه','سعرات','بروتين','كرياتين','مكمل','مكملات','فيتامين','نوم','النوم','انام','ينام','ساعات النوم','تعافي','politics','election','president','government','news','weather','travel','hotel','restaurant','recipe','cooking','programming','code','stocks','investment','religion','medical','medicine','medication','diagnosis','treatment','disease','diabetes','pregnancy','injury','pain','dizziness','nutrition','diet','food','meal','calorie','calories','protein','creatine','supplement','supplements','vitamin','sleep','recovery'
];
function isExerciseOnlyQuestion(text){const v=normalize(text);if(!v)return false;if(blockedTerms.some(k=>v.includes(normalize(k))))return false;return exerciseTerms.some(k=>v.includes(normalize(k)))}
function scopeReply(text){return hasArabic(text)?'أنا مخصص لأسئلة التمارين فقط: طريقة أداء التمرين، العضلات المستهدفة، المعدات، المجموعات والتكرارات، الإحماء والسلامة أثناء التمرين.':'I only answer exercise questions: exercise form, target muscles, equipment, sets and reps, warm-up, and exercise safety.'}
function cleanReply(text){return String(text||'').replace(/\r\n/g,'\n').replace(/\*\*(.*?)\*\*/g,'$1').replace(/__(.*?)__/g,'$1').replace(/`([^`]+)`/g,'$1').replace(/^#{1,6}\s+/gm,'').replace(/^\s*[-*]\s+/gm,'• ').replace(/\n{3,}/g,'\n\n').trim()}
function formatMsg(el,text,who){const value=who==='user'?String(text||''):cleanReply(text);el.textContent=value;const rtl=hasArabic(value);el.dir=rtl?'rtl':'ltr';el.lang=rtl?'ar':'en';el.style.textAlign=rtl?'right':'left'}
function mount(){if(document.getElementById('moAiBtn'))return;
const style=document.createElement('style');style.textContent=`#moAiBtn{position:fixed;z-index:260;right:18px;bottom:82px;width:56px;height:56px;visibility:visible!important;opacity:1!important;pointer-events:auto!important;border:1px solid #62d4ff;border-radius:50%;background:linear-gradient(135deg,#17b5ff,#078cff);color:#fff;font-size:25px;box-shadow:0 12px 32px #0008;cursor:pointer}#moAiPanel{position:fixed;z-index:261;right:16px;bottom:148px;width:min(390px,calc(100vw - 24px));height:min(570px,72vh);display:none;flex-direction:column;background:#081925;border:1px solid #17465e;border-radius:18px;box-shadow:0 24px 70px #000b;overflow:hidden;color:#f5fbff}#moAiPanel.open{display:flex}.moAiHead{display:flex;align-items:center;justify-content:space-between;padding:13px 14px;background:#0a1d29;border-bottom:1px solid #17465e}.moAiHead b{color:#62d4ff}.moAiClose{border:0;background:transparent;color:#fff;font-size:22px;cursor:pointer}.moAiMsgs{flex:1;overflow:auto;padding:12px;display:flex;flex-direction:column;gap:9px}.moAiMsg{max-width:88%;padding:9px 11px;border-radius:13px;white-space:pre-wrap;font-size:14px;line-height:1.75;overflow-wrap:anywhere;unicode-bidi:plaintext}.moAiMsg[dir=rtl]{font-family:inherit;letter-spacing:0}.moAiUser{align-self:flex-end;background:#0d8fd1;color:#fff}.moAiBot{align-self:flex-start;background:#0d2634;border:1px solid #17465e}.moAiForm{display:flex;gap:7px;padding:10px;border-top:1px solid #17465e;background:#071722}.moAiInput{flex:1;min-width:0;border:1px solid #28536b;background:#0a2230;color:#fff;border-radius:10px;padding:10px;outline:none}.moAiSend{border:0;border-radius:10px;padding:9px 13px;background:#0da7ff;color:#fff;font-weight:900;cursor:pointer}.moAiSend:disabled{opacity:.55}.moAiNote{padding:0 11px 9px;color:#8fa7b4;font-size:10px}.moAiOpen #installBanner{display:none!important}@media(max-width:520px){#moAiBtn{right:12px;bottom:76px}#moAiPanel{inset:8px;width:auto;height:auto;max-height:none;border-radius:14px}.moAiMsg{max-width:92%;font-size:14px;line-height:1.8}.moAiForm{padding-bottom:max(10px,env(safe-area-inset-bottom))}}`;document.head.appendChild(style);
const btn=document.createElement('button');btn.id='moAiBtn';btn.type='button';btn.setAttribute('aria-label','MO Fitness AI');btn.setAttribute('aria-controls','moAiPanel');btn.setAttribute('aria-expanded','false');btn.textContent='🤖';
const panel=document.createElement('section');panel.id='moAiPanel';panel.setAttribute('role','dialog');panel.setAttribute('aria-label','MO Fitness AI');panel.innerHTML=`<div class="moAiHead"><b>MO Fitness AI</b><button class="moAiClose" type="button" aria-label="${T('إغلاق','Close')}">×</button></div><div class="moAiMsgs" aria-live="polite"></div><form class="moAiForm"><input class="moAiInput" maxlength="500" autocomplete="off" aria-label="${T('سؤالك','Your question')}" placeholder="${T('اكتب سؤالك...','Type your question...')}"><button class="moAiSend" type="submit">${T('إرسال','Send')}</button></form><div class="moAiNote">${T('إرشادات لياقة عامة وليست تشخيصًا أو علاجًا طبيًا. لا ترسل معلومات شخصية أو حساسة.','General fitness guidance, not medical diagnosis or treatment. Do not send personal or sensitive information.')}</div>`;
document.body.append(panel,btn);const msgs=panel.querySelector('.moAiMsgs'),form=panel.querySelector('form'),input=panel.querySelector('input'),send=panel.querySelector('.moAiSend'),close=panel.querySelector('.moAiClose');
function setOpen(open){panel.classList.toggle('open',open);document.body.classList.toggle('moAiOpen',open);btn.setAttribute('aria-expanded',String(open));if(open)input.focus()}
btn.onclick=()=>setOpen(!panel.classList.contains('open'));close.onclick=()=>setOpen(false);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel.classList.contains('open'))setOpen(false)});
const add=(text,who)=>{const d=document.createElement('div');d.className='moAiMsg '+(who==='user'?'moAiUser':'moAiBot');formatMsg(d,text,who);msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight;return d};
add(T('مرحبًا! أنا مساعد MO Fitness للتمارين فقط. اسألني عن طريقة أداء التمارين، العضلات، المعدات، المجموعات والتكرارات.','Hi! I’m the MO Fitness exercise-only assistant. Ask about exercise form, muscles, equipment, sets, and reps.'),'bot');
form.onsubmit=async e=>{e.preventDefault();const message=input.value.trim();if(!message||send.disabled)return;add(message,'user');input.value='';if(!isExerciseOnlyQuestion(message)){add(scopeReply(message),'bot');input.focus();return}send.disabled=true;input.disabled=true;const wait=add(T('جاري التفكير…','Thinking…'),'bot');const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000);const scopedMessage=`Answer ONLY about exercise form, target muscles, exercise equipment, sets/reps, warm-up, stretching, and exercise safety. Never answer unrelated topics, nutrition, medical diagnosis/treatment, politics, news, coding, travel, cooking, finance, religion, or general knowledge. If the request is unrelated or mixed with an unrelated request, reply only that MO Fitness AI handles exercise questions. User question: ${message}`;try{const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({message:scopedMessage,originalMessage:message,scope:'exercise-only'})});const data=await r.json().catch(()=>({}));formatMsg(wait,r.ok&&data.reply?data.reply:(data.error||T('تعذر الاتصال بالمساعد حاليًا.','Unable to reach the assistant right now.')),'bot')}catch(_){formatMsg(wait,T('تعذر الاتصال بالمساعد حاليًا. حاول مرة أخرى.','Unable to reach the assistant right now. Please try again.'),'bot')}finally{clearTimeout(timeout);send.disabled=false;input.disabled=false;input.focus();msgs.scrollTop=msgs.scrollHeight}};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();window.addEventListener('pageshow',mount);document.addEventListener('visibilitychange',()=>{if(!document.hidden)mount()});
})();