/* MO Fitness AI — bilingual chat UI */
(()=>{
const ENDPOINT='https://mo-fitness-ai.moh-oglah.workers.dev';
const ar=()=>document.documentElement.lang!=='en';
const T=(a,e)=>ar()?a:e;
function mount(){if(document.getElementById('moAiBtn'))return;
const style=document.createElement('style');style.textContent=`#moAiBtn{position:fixed;z-index:145;right:18px;bottom:82px;width:56px;height:56px;border:1px solid #62d4ff;border-radius:50%;background:linear-gradient(135deg,#17b5ff,#078cff);color:#fff;font-size:25px;box-shadow:0 12px 32px #0008;cursor:pointer}#moAiPanel{position:fixed;z-index:146;right:16px;bottom:148px;width:min(390px,calc(100vw - 24px));height:min(570px,72vh);display:none;flex-direction:column;background:#081925;border:1px solid #17465e;border-radius:18px;box-shadow:0 24px 70px #000b;overflow:hidden;color:#f5fbff}#moAiPanel.open{display:flex}.moAiHead{display:flex;align-items:center;justify-content:space-between;padding:13px 14px;background:#0a1d29;border-bottom:1px solid #17465e}.moAiHead b{color:#62d4ff}.moAiClose{border:0;background:transparent;color:#fff;font-size:22px;cursor:pointer}.moAiMsgs{flex:1;overflow:auto;padding:12px;display:flex;flex-direction:column;gap:9px}.moAiMsg{max-width:88%;padding:9px 11px;border-radius:13px;white-space:pre-wrap;font-size:14px;line-height:1.55}.moAiUser{align-self:flex-end;background:#0d8fd1;color:#fff}.moAiBot{align-self:flex-start;background:#0d2634;border:1px solid #17465e}.moAiForm{display:flex;gap:7px;padding:10px;border-top:1px solid #17465e;background:#071722}.moAiInput{flex:1;min-width:0;border:1px solid #28536b;background:#0a2230;color:#fff;border-radius:10px;padding:10px;outline:none}.moAiSend{border:0;border-radius:10px;padding:9px 13px;background:#0da7ff;color:#fff;font-weight:900;cursor:pointer}.moAiSend:disabled{opacity:.55}.moAiNote{padding:0 11px 9px;color:#8fa7b4;font-size:10px}@media(max-width:520px){#moAiBtn{right:12px;bottom:76px}#moAiPanel{right:12px;bottom:140px;height:65vh}}`;document.head.appendChild(style);
const btn=document.createElement('button');btn.id='moAiBtn';btn.type='button';btn.setAttribute('aria-label','MO Fitness AI');btn.textContent='🤖';
const panel=document.createElement('section');panel.id='moAiPanel';panel.innerHTML=`<div class="moAiHead"><b>MO Fitness AI</b><button class="moAiClose" type="button">×</button></div><div class="moAiMsgs"><div class="moAiMsg moAiBot">${T('مرحبًا! أنا مساعد MO Fitness. اسألني عن التمارين، التدريب، التعافي أو التغذية الرياضية العامة.','Hi! I’m the MO Fitness assistant. Ask me about exercise, training, recovery, or general sports nutrition.')}</div></div><form class="moAiForm"><input class="moAiInput" maxlength="500" autocomplete="off" placeholder="${T('اكتب سؤالك...','Type your question...')}"><button class="moAiSend" type="submit">${T('إرسال','Send')}</button></form><div class="moAiNote">${T('إرشادات لياقة عامة وليست تشخيصًا أو علاجًا طبيًا.','General fitness guidance, not medical diagnosis or treatment.')}</div>`;
document.body.append(panel,btn);const msgs=panel.querySelector('.moAiMsgs'),form=panel.querySelector('form'),input=panel.querySelector('input'),send=panel.querySelector('.moAiSend');
btn.onclick=()=>{panel.classList.toggle('open');if(panel.classList.contains('open'))input.focus()};panel.querySelector('.moAiClose').onclick=()=>panel.classList.remove('open');
const add=(text,who)=>{const d=document.createElement('div');d.className='moAiMsg '+(who==='user'?'moAiUser':'moAiBot');d.textContent=text;msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight;return d};
form.onsubmit=async e=>{e.preventDefault();const message=input.value.trim();if(!message)return;add(message,'user');input.value='';send.disabled=true;const wait=add(T('جاري التفكير…','Thinking…'),'bot');try{const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})});const data=await r.json().catch(()=>({}));wait.textContent=r.ok&&data.reply?data.reply:(data.error||T('تعذر الاتصال بالمساعد حاليًا.','Unable to reach the assistant right now.'))}catch(_){wait.textContent=T('تعذر الاتصال بالمساعد حاليًا.','Unable to reach the assistant right now.')}finally{send.disabled=false;input.focus();msgs.scrollTop=msgs.scrollHeight}};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();