/* MO Fitness — English detail content */
(function(){
const en={
bench:['Flat bench, Olympic barbell, plates and rack. Set the hooks so the bar can be unracked without lifting your shoulders. Lie with eyes roughly under the bar, upper back and glutes on the bench, and feet firmly planted.','Breathe in and brace before lowering; exhale gradually while pressing past the hardest point.','Use safety arms or a spotter for challenging loads. Never bounce the bar off your chest or lift your glutes.'],
dbpress:['Stable flat bench and two equal dumbbells. Sit at the edge with each dumbbell on a thigh, then use your thighs to guide them into position as you lie back.','Inhale while lowering and exhale while pressing up.','Use a shoulder-friendly range. Do not lower beyond the point where you can keep the shoulders stable.'],
pushup:['Use a firm floor or mat. Place hands slightly wider than shoulder width and extend the legs back onto the toes.','Inhale on the way down and exhale as you push up.','Stop the set when body alignment breaks. Raise the hands on a stable surface to make the exercise easier.'],
lat:['Use a lat-pulldown machine and overhead bar. Select the load and adjust the thigh pad so your legs stay secure without painful pressure.','Exhale while pulling down and inhale during the controlled return.','Do not pull behind the neck or swing the torso to move more weight.'],
row:['Use a seated cable row or low cable with a suitable handle. Place your feet securely and keep a small bend in the knees.','Exhale while rowing and inhale during the return.','Do not let the weight stack yank you forward or use lower-back momentum.'],
onearm:['Use one dumbbell and a stable bench. Support one hand and knee, or use a secure one-hand stance, with the other foot planted for balance.','Exhale while rowing and inhale while lowering the dumbbell.','Do not rotate the torso or shrug the working shoulder. Reduce the load if you cannot stay stable.'],
shoulder:['Use two dumbbells and a high-back bench close to upright. Sit with your back supported and both feet planted.','Exhale while pressing overhead and inhale while lowering.','Do not compensate for a heavy load by excessively arching the lower back or driving with the legs.'],
lateral:['Use light-to-moderate dumbbells. Stand in a comfortable stance with soft knees, or sit on a stable bench to reduce momentum.','Exhale while raising and inhale while lowering.','Reduce the weight if you need to swing or shrug the shoulders toward the ears.'],squat:['Use a squat rack, barbell, plates and safety arms. Set the hooks just below shoulder height and the safeties at an appropriate level.','Take a deep breath and brace before descending; exhale gradually near the end of the ascent.','Use the safety arms. Keep knees tracking with the toes and the whole foot grounded; do not chase depth at the expense of position.'],
rdl:['Use a barbell and plates. Start standing with the bar close to the thighs, feet around hip width and knees softly bent.','Inhale and brace before the hinge; exhale gradually as you return to standing.','This is a hip hinge, not a squat. Keep the spine neutral and the bar close to the body.'],
legpress:['Use a leg-press machine. Select the load, adjust the seat/backrest, and place both feet securely on the platform.','Inhale while lowering and exhale while pressing.','Safety mechanisms vary by machine. Follow its instructions and keep the pelvis against the pad.'],
curl:['Use two equal dumbbells. Stand securely or sit on a bench with a load you can curl without hip or shoulder momentum.','Exhale while curling and inhale while lowering.','Do not swing the dumbbells with the hips or back. Reduce the load if momentum is required.'],
triceps:['Use a cable station with a straight bar or rope. Set the pulley high and choose a controllable load.','Exhale while pressing down and inhale during the return.','Do not use a load that forces you to lean over the handle. Control the weight stack on the return.'],
plank:['Use a mat or firm floor. Place forearms down with elbows roughly under the shoulders, extend the legs and support yourself on the toes.','Breathe normally throughout the hold; do not hold your breath.','Position quality matters more than duration. Shorten the hold or use an easier variation if sharp pain occurs.'],
deadbug:['Use a mat. Lie on your back, raise the arms toward the ceiling and bring the hips and knees to roughly 90 degrees.','Exhale slowly while extending the limbs and inhale as you return to center.','Reduce the arm or leg range immediately if the lower back starts arching out of control.'],
carry:['Use two dumbbells or farmer handles and a clear walking path. Position the loads beside your feet before lifting.','Breathe steadily while maintaining abdominal tension; do not hold your breath for the whole carry.','Keep the route clear, do not run with the weights, and use a load that does not pull you into a dangerous side lean.']
};
const tips={bench:['Keep the upper back tight','Do not bounce the bar','Use a fully controllable load'],dbpress:['Do not bang the dumbbells together','Stay controlled','Use a comfortable elbow angle'],pushup:['Brace the core','Keep elbows at a comfortable angle','Keep the neck neutral'],lat:['Never pull behind the neck','Avoid swinging','Initiate with the shoulders'],row:['Keep shoulders down','Do not rock the torso','Drive elbows back'],onearm:['Do not rotate the torso','Row toward the hip','Keep the neck stable'],shoulder:['Avoid excessive back arch','Plant the feet','Control the descent'],lateral:['Use a light load','Lead with the elbows','Avoid swinging'],squat:['Brace before descending','Keep the whole foot down','Use a suitable depth'],rdl:['Keep the bar close','Maintain a neutral spine','Hinge from the hips'],legpress:['Keep pelvis down','Do not hard-lock knees','Use a safe depth'],curl:['Keep elbows stable','Control the lowering','Do not swing'],triceps:['Keep elbows fixed','Use a stable load','Use full controlled range'],plank:['Keep breathing','Do not let hips sag','Start with short holds'],deadbug:['Move slowly','Keep lower back controlled','Use only a controllable range'],carry:['Keep shoulders down','Do not lean sideways','Use steady steps']};
const mistakes={bench:['Excessive elbow flare','Feet leaving the floor','Dropping the bar too fast'],dbpress:['Lowering beyond control','Excessive lower-back arch','Loose wrists'],pushup:['Hips sagging','Lifting the head','Very short range'],lat:['Leaning back excessively','Pulling only with the arms','Letting the weight snap back'],row:['Shrugging','Torso momentum','Short range'],onearm:['Rotating the body','Shrugging the shoulder','Using momentum'],shoulder:['Unintended leg drive','Excessive back arch','Dropping too fast'],lateral:['Shrugging','Using momentum','Using too much weight'],squat:['Knees collapsing inward','Heels lifting','Losing trunk brace'],rdl:['Turning it into a squat','Rounding the back','Letting the bar drift away'],legpress:['Depth that lifts the pelvis','Knees collapsing inward','Releasing the platform too fast'],curl:['Swinging','Elbows drifting forward','Incomplete range'],triceps:['Moving the shoulder','Excessive forward lean','Half repetitions'],plank:['Hips too high','Lower back sagging','Holding the breath'],deadbug:['Lower back arching','Moving too fast','Holding the breath'],carry:['Moving too fast','Side bending','Uncontrolled grip']};function apply(){if(!window.exercises)return setTimeout(apply,50);exercises.forEach(e=>{if(en[e.id]){e.setupEn=en[e.id][0];e.breathEn=en[e.id][1];e.safetyEn=en[e.id][2];}e.tipsEn=tips[e.id]||[];e.mistEn=mistakes[e.id]||[];});}
apply();
})();